### ISSUE TITLE
Add package to melpa

### ISSUE THREAD

**Issue by ericdallo** [wandersoncferreira/cljr-ivy#1]
What do you think about adding the package to `https://github.com/melpa/melpa`?

**Comment by wandersoncferreira** [comment]
I can do that, I will submit a PR tonight! Thanks

**Comment by wandersoncferreira** [comment]
For reference https://github.com/melpa/melpa/pull/6943

**Comment by ericdallo** [comment]
Thank you!

**Comment by wandersoncferreira** [comment]
Merged! thanks
